export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  SELLER = 'SELLER',
  FARMER = 'FARMER',
  ARTISAN = 'ARTISAN',
  EDUCATOR = 'EDUCATOR',
  DELIVERY_PARTNER = 'DELIVERY_PARTNER',
  ADMIN = 'ADMIN',
}
